<a href="https://colab.research.google.com/github/coder174-ops/Ensemble/blob/main/StackingClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [ ]:
df=sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
X=df.drop('species',axis=1)
y=df['species']

In [ ]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [ ]:
le=LabelEncoder()
y_encoded=le.fit_transform(y)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.20, random_state=42,stratify=y_encoded)

In [ ]:
base_learners = [
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('svm', SVC(probability=True,kernel='rbf',random_state=42)),
    ('lr', LogisticRegression(max_iter=1000))
]

In [ ]:
meta_learner=LogisticRegression(max_iter=1000)

In [ ]:
stacking_clf = StackingClassifier(
    estimators=base_learners,
    final_estimator=meta_learner,
    cv=5
)

In [ ]:
stacking_clf.fit(X_train, y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svm', SVC(probability=True, random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=LogisticRegression(max_iter=1000))

In [ ]:
y_pred=stacking_clf.predict(X_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.9666666666666667

# Bagging(Random forest classifier)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf_model=RandomForestClassifier(
    n_estimators=100,  #no. of trees
    max_depth=None,    #let trees grow fully
    random_state=42
)

In [ ]:
rf_model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred=rf_model.predict(X_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.9

# **Boosting(adaBoostclassifier,GradientBoostingClassifier,XGBoost)**

In [ ]:
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier

In [ ]:
import xgboost as xgb

In [ ]:
model_ada=AdaBoostClassifier(n_estimators=100,random_state=42)

In [ ]:
model_ada.fit(X_train,y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [ ]:
y_pred=model_ada.predict(X_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.9333333333333333

In [ ]:
model_gb=GradientBoostingClassifier(n_estimators=100, learning_rate=0.1,random_state=42)

In [ ]:
model_gb.fit(X_train,y_train)

GradientBoostingClassifier(random_state=42)

In [ ]:
y_pred=model_gb.predict(X_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.9666666666666667

In [ ]:
model_xgb=xgb.XGBClassifier(n_estimators=100,learning_rate=0.1,
              max_depth=3,
              eval_metric='mlogloss',
              random_state=42)

In [ ]:
model_xgb.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [ ]:
y_pred=model_xgb.predict(X_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.9333333333333333